config/routes.rb
Rails.application.routes.draw do

  root to: 'top#index'

  devise_for :users
  get 'admin/users'              => 'users#index'
  get 'admin/users/show/:id'     => 'users#show'

  resources :owners

  get  'cars/searchword'  => 'cars#searchword'
  post 'cars/searchword'  => 'cars#searchword'
  post 'cars/searchid'    => 'cars#searchid'
  post 'cars/fileupload'  => 'cars#fileupload'
  get  'cars/:id/mail'    => 'cars#mail', as: :mail_car
  resources :cars

end

app/models/car.rb
class Car < ActiveRecord::Base
  belongs_to :owner

  def expired?
    Time.now > created_at + 1.days + 12.hours + 50.minutes
  end
end

app/models/owner.rb
class Owner < ActiveRecord::Base
  has_many :cars
  has_one :user
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :owner

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         :confirmable

  validates :name, presence: true, uniqueness: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :name
    end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy, :mail]

  # 全ページ、ログイン必須
  before_filter  :authenticate_user!, except: []


  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params.strip_tags)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  # POST /cars/searchword
  def searchword
    @cars = search_cars_by_word params[:search_word]
  end

  # POST /cars/searchid
  def searchid
    @cars = search_cars_by_id params[:search_id]
  end


  # POST /cars/fileupload
  def fileupload
    save_file params[:files] if params[:files]
    
    @cars = Car.all
    render :action => 'index'
  end


  # /cars/1/mail
  def mail
    to = params[:mail_to] || 'ta_kondoh@actis.co.jp'
    PostMailer.post_carinfo(to, @car).deliver_now

    @cars = Car.all
    render :action => 'edit'
  end


  private
    #
    def save_file files
      files.each do |file|
        ImageFile.new(file).name('hoge').resize().store()
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:name, :owner_id)
    end

    # search cars by word (e.g 'toyo niss'), cond('and' or 'or')
    def search_cars_by_word (word, cond = 'or')
      words = word.split.map{|v| "%#{v}%"}                     # 'toyo niss' --> ['%toyo%', '%niss%']
      query = (['name like ?'] * words.size).join(" #{cond} ") # 'name like ? or name like ? or ...'

      Car.where([query, *words]).map.to_a
    end

    # search cars by id (e.g '1,2'), cond('and' or 'or')
    def search_cars_by_id (id, cond = 'or')
      ids = id.split(',').map(&:strip)                       # '1, 2' --> ['1', '2']
      query = (['id = ?'] * ids.size).join(" #{cond} ")      # 'id = ? or id = ? or ...'

      Car.where([query, *ids]).map.to_a
    end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  before_action :set_owner, only: [:show, :edit, :update, :destroy]

  # 全ページ、ログイン必須
  before_filter  :authenticate_user!, except: []

  # GET /owners
  # GET /owners.json
  def index
    @owners = Owner.all
  end

  # GET /owners/1
  # GET /owners/1.json
  def show
  end

  # GET /owners/new
  def new
    @user = current_user
    @owner = Owner.new
  end

  # GET /owners/1/edit
  def edit
  end

  # POST /owners
  # POST /owners.json
  def create
    @owner = Owner.new(owner_params)

    respond_to do |format|
      if @owner.save
        format.html { redirect_to @owner, notice: 'Owner was successfully created.' }
        format.json { render :show, status: :created, location: @owner }
      else
        format.html { render :new }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end

    # アカウントユーザのオーナー登録の場合、user.owner_idにユーザのIDを設定
    if params[:owner][:own]
      user = current_user
      user.owner_id = @owner.id
      user.save
    end
  end

  # PATCH/PUT /owners/1
  # PATCH/PUT /owners/1.json
  def update
    respond_to do |format|
      if @owner.update(owner_params)
        format.html { redirect_to @owner, notice: 'Owner was successfully updated.' }
        format.json { render :show, status: :ok, location: @owner }
      else
        format.html { render :edit }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /owners/1
  # DELETE /owners/1.json
  def destroy
    @owner.destroy
    respond_to do |format|
      format.html { redirect_to owners_url, notice: 'Owner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_owner
      @owner = Owner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def owner_params
      params.require(:owner).permit(:name, :car_id)
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  before_action :ownership, only: [:show]

  # GET /cars
  # GET /cars.json
  def index
    @user = current_user
    @owners = Owner.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def ownership
      @car = Owner.find(params[:id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, only: [:show, :index]

  def index
    @users = User.all
  end

  def show
  end

  private
    def authorize
      @user = current_user
      unless @user && @user.name == 'admin'
        redirect_to controller: 'top', action: 'index'
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  ### monkey patch

  String.class_eval do
    def strip_tags
      ActionController::Base.helpers.strip_tags self
    end
  end

  ActionController::Parameters.class_eval do
    def strip_tags
      self.each do |key, value|
        self[key] = value.strip_tags
      end
      self
    end
  end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cars/_form.html.slim
= form_for(@car) do |f|
    - if @car.errors.any?
        #error_explanation
            h2 = pluralize(@car.errors.count, "error")
                | prohibited this car from being saved
            ul - @car.errors.full_messages.each do |message|
                = message
    .field
         = f.label :name
         = f.text_field :name
    .field
         = f.label :owner_id
         = f.text_field :owner_id

    .actions
         = f.submit button_name, {class: 'btn btn-primary active'}

app/views/cars/_search.html.slim
.row
    .col-md-12
        table.table class='table-striped table-bordered'
            thead
                tr
                    th.col-md-1 colspan="1" id
                    th.col-md-4 colspan="1" name
            tbody
                - @cars.each do |car|
                    tr
                        td.col-md-1 = car.id
                        td.col-md-4 = car.name
    

app/views/cars/edit.html.slim
h1 Editing Car

= render 'form', button_name: '編集'

= link_to 'Show', @car,      {class: 'btn btn-primary active'}
= link_to 'Back', cars_path, {class: 'btn btn-primary active'}

app/views/cars/index.html.slim
p#notice
  = notice


div#hoge
    | hoge
    .col-md-12#fuga1
        | fuga1
    .col-md-12#fuga2
        | fuga2

div#posi x, y


h1 Listing Cars


.container
    .row
        .col-md-12
            = form_tag '/cars/searchword' do
                | search by word
                = text_field_tag 'search_word'
                = submit_tag '検索', method: :post
        .col-md-12
            = form_tag '/cars/searchid' do
                | search by id
                = text_field_tag 'search_id'
                = submit_tag '検索', method: :post
        .col-md-12
            = form_tag '/cars/searchword', method: 'get' do
                | search by word. with URL parameter
                = text_field_tag 'search_word'
                = button_tag '検索', id: 'search_word_button'
        .col-md-12
            = form_tag '/cars/fileupload', :multipart => true do
                | search by id
                = file_field_tag 'files[]'
                = file_field_tag 'files[]'
                = submit_tag 'ファイルアップロード', method: :post

    .row
        .col-md-12
            | メール
            = text_field_tag('mail_to')

    .row
        .col-md-12
            table.table class='table-striped table-bordered'
                thead
                    tr
                        th.col-md-1 colspan="1" id
                        th.col-md-2 colspan="1" name
                        th.col-md-3 colspan="1" created_at
                        th.col-md-1 colspan="1" old?
                        th.col-md-1 colspan="4"
                tbody
                    - @cars.each do |car|
                        tr
                            td.col-md-1 = car.id
                            td.col-md-2 = car.name
                            td.col-md-3 = car.created_at
                            td.col-md-1 = car.expired? ? 'old' : ''
                            td.col-md-1 = link_to '詳細',   car,                {                 class: 'btn btn-primary active btn-sm'}
                            td.col-md-1 = link_to '編集',   edit_car_path(car), {                 class: 'btn btn-primary active btn-sm'}  
                            td.col-md-1 = link_to '削除',   car,                {method: :delete, class: 'btn btn-primary active btn-sm'}
                            td.col-md-1 = link_to 'メール', mail_car_path(car), {                 class: 'btn btn-primary active btn-sm mail', id: "#{car.id}"}

    .row
        .col-md-12
            = link_to '新規', new_car_path, {class: 'btn btn-primary active'}

#background-black background-black

.row style="border: solid 1px"
    .col-md-4
        button#toggle toggle
    .col-md-4
        p.toggle yes
    .col-md-4
        p.toggle style="display: none" no

.row
    .col-md-12
         .row style="border: solid 1px"
           .col-md-12#focusblur
               pre#bivration style="position: absolute; left: 0px"
                   | hogehoge
        



br
br
br

opal:
    Element['#background-black'].on(:click) do |evt|     
       Element.find('.container').css 'background-color', '#808080'
    end

    Element['#hoge'].instance_eval do |hoge|
      hoge.on :click do |event|
        children.each{|child| child.css 'color', '#ff0000'}
        Element['#posi'].text = "#{event.page_x} #{event.page_y}"
      end
    end

    Element['#toggle'].on :click do |event|
      Element['.toggle'].toggle
    end

    Element['#focusblur'].blur do |event|
      Element['bivration'].css 'left', '10px'
      Element['bivration'].delay(1000).css 'left', '20px'
    end

    Element['#focusblur'].focus do |event|
      Element['bivration'].css 'left', '20px'
    end

    Element['.mail'].on :click do |event|
      elem = event.element
      addr = Element['#mail_to'].value
      elem[:href] = "#{elem[:href]}?mail_to=#{addr}" if addr && ! addr.empty?
    end

app/views/cars/new.html.slim
h1 New Car

= render 'form', button_name: '作成'

= link_to 'Back', cars_path, {class: 'btn btn-primary active'}

app/views/cars/searchid.html.slim
p#notice
  = notice

h1 Cars Search Result

.container
    = render 'search', cars: @cars
    
    .row
        .col-md-12
            = link_to '戻る', cars_path, {class: 'btn btn-primary active'}

app/views/cars/searchword.html.slim
p#notice
  = notice

h1 Cars Search Result

.container
    = render 'search', cars: @cars
    
    .row
        .col-md-12
            = link_to '戻る', cars_path, {class: 'btn btn-primary active'}

app/views/cars/show.html.slim
p#notice
    = notice


.container
    .row
        .col-md-2 style="margin-bottom: 20px; border: solid 1px; border-radius: 3px 0px 0px 3px"
            strong Name
        .col-md-4 style="margin-bottom: 20px; border: solid 1px; border-radius: 0px 3px 3px 0px"
            = @car.name
        
    .row
        = link_to 'Edit', edit_car_path(@car), {class: 'btn btn-primary active', style: 'margin-left:5px; margin-right:5px;'}
        = link_to 'Back', cars_path,           {class: 'btn btn-primary active', style: 'margin-left:5px; margin-right:5px;'}

app/views/layouts/application.html.slim
doctype html
html
    head
        title Tmp05
        = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
        = javascript_include_tag 'application', 'data-turbolinks-track' => true
        = csrf_meta_tags
    body
        nav.navbar.navbar-fixed-top.navbar-default role="navigation"
            .container-fluid
                .navbar-header
                    .navbar-brand
                        = link_to 'Tmp05', '/'
                .collapse.navbar-collapse
                    ul.nav.navbar-nav.navbar-right
                        - if user_signed_in?
                            li.active
                                = link_to current_user.name, edit_user_registration_path
                            li
                                = link_to 'sign_out', destroy_user_session_path, method: :delete
                        - else
                            li.active
                                = link_to 'sign_up', new_user_registration_path
                            li
                                = link_to 'sign_in', new_user_session_path

        p.notice = notice
        p.alert  = alert
        = yield

app/views/owners/_form.html.slim
= form_for @owner do |f|
  - if @owner.errors.any?
    #error_explanation
      h2 = "#{pluralize(@owner.errors.count, "error")} prohibited this owner from being saved:"
      ul
        - @owner.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .actions = f.submit

app/views/owners/edit.html.slim
h1 Editing owner

== render 'form'

= link_to 'Show', @owner
'|
= link_to 'Back', owners_path

app/views/owners/index.html.slim
h1 Listing owners

table
  thead
    tr
      th Name
      th Car
      th
      th
      th

  tbody
    - @owners.each do |owner|
      tr
        td = owner.name
        td = link_to 'Show', owner
        td = link_to 'Edit', edit_owner_path(owner)
        td = link_to 'Destroy', owner, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Owner', new_owner_path

app/views/owners/new.html.slim
h1 New owner

= form_tag '/owners' do
    input type='hidden' name='owner[own]'  id='owner_own'  value="own"
    input type='hidden' name='owner[name]' id='owner_name' value="#{@user.name}"
    = submit_tag 'create me', method: :post
br
br

== render 'form'

= link_to 'Back', owners_path

app/views/owners/show.html.slim
p#notice = notice

p
  strong Name:
  = @owner.name

= link_to 'Edit', edit_owner_path(@owner)
'|
= link_to 'Back', owners_path

app/views/top/_form.html.slim
= form_for(@owner) do |f|
    - if @owner.errors.any?
        #error_explanation
            h2 = pluralize(@owner.errors.count, "error")
                | prohibited this owner from being saved
            ul - @owner.errors.full_messages.each do |message|
                = message
    .field
         = f.label :name
         = f.text_field :name

    .actions
         = f.submit button_name, {class: 'btn btn-primary active'}

app/views/top/index.html.slim
p#notice
  = notice


h1 Listing Car Ownership


.container
    .row
        .col-md-12
            - @owners.each do |owner|
                = "#{owner.name} (Owner Id : #{owner.id})"
                = "Mine!" if owner.user && @user && owner.user.id == @user.id
                <br>
                    .row
                        .col-md-12
                            .row
                            .col-md-12
                                table.table class='table-striped table-bordered'
                                    thead
                                        tr
                                            th.col-md-1 colspan="1" car id
                                            th.col-md-1 colspan="1" car name
                                    tbody
                                        - owner.cars.each do |car|
                                            tr
                                                td.col-md-1 = car.id
                                                td.col-md-1 = car.name

    .row
        | 編集ページ
        .col-md-12
            = link_to 'cars', cars_path
        .col-md-12
            = link_to 'owners', owners_path

app/views/users/index.html.slim
h1 Users#index
p Find me in app/views/users/index.html.slim

table.table.table-striped.table-bordered
    thead
        th Id
        th Name
        th Owner.id
        th Created at
        th Updated at
    tbody
    - @users.each do |user|
        tr
            td = user.id
            td = user.name
            td = user.owner ? user.owner.id : nil
            td = user.created_at
            td = user.updated_at

app/views/users/show.html.slim
h1 Users#show
p Find me in app/views/users/show.html.slim